# fly.toml app configuration file generated for ms-email-notification-v1 on 2024-04-23T10:45:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ms-email-notification-v1'
primary_region = 'bog'

[build]
  image = 'jamp1992/ms-email-notification:v4'

[env]
  ATTACHMENT_FILENAME = 'consolidated-report.pdf'
  EMAIL_ATTACHMENT_SET_FROM = 'contacto@invexdijin.com'
  EMAIL_ATTACHMENT_SET_SUBJECT = 'Reporte consolidado'
  EMAIL_CONTACT_SET_SUBJECT = 'Formulario de contacto'
  EMAIL_CONTACT_SET_TO = 'contacto@invexdijin.com'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
