# fly.toml app configuration file generated for ms-email-notification-holy-pine-5672 on 2024-01-21T14:30:39-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ms-email-notification-holy-pine-5672"
primary_region = "bog"

[build]
  image = "jamp1992/ms-email-notification:v2"

[env]
  ATTACHMENT_FILENAME = "consolidated-report.pdf"
  EMAIL_ATTACHMENT_SET_FROM = "john1992alex@gmail.com"
  EMAIL_ATTACHMENT_SET_SUBJECT = "Reporte consolidado"
  EMAIL_CONTACT_SET_SUBJECT = "Formulario de contacto"
  EMAIL_CONTACT_SET_TO = "john1992alex@gmail.com"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
